	version:"3.8"

	services:
	  mysql:
		container_name:mysql
		image:mysql
		environment:
		  - MYSQL_ROOT_PASSWORD: "root"
		  - MYSQL_DATABASE: "devops"
		port:
		  - "3306:3306"
		networks:
		  - mynetwork
		volumes:
		  - myapp-data:/var/lib/mysql
		healthcheck:
		  test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
		  interval: 10s
		  timeout: 5s
		  retries: 5
		  start_period: 60s

	  
	  flaskapp:
		build:
		  context:.
		container_name:flaskapp
		environment:
		  - MYSQL_HOST:mysql
		  - MYSQL_USER:root
		  - MYSQL_PASSWORD:root
		  - MYSQL_DB:devops
		ports:
		  - "5000:5000"
		networks:
		  - mynetwork
		dependent_on:
		  - mysql
		healthcheck:
		  test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
		  interval: 10s
		  timeout: 5s
		  retries: 5
		  start_period: 30s
		  
	networks:
	  mynetwork:
	volumes:
	  myapp-data:
